## Code for the paper 'Psychopathic traits and their relationship with vulnerability to 
## general psychopathology in a young adult sample’ (Carlisi, Fielder et al., in prep)

# Jennifer Fielder - jennifer.fielder.21@ucl.ac.uk
# May 2023

# Load dependencies
library(lavaan)
library(dplyr)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
library(ggplot2)
library(car)
library(lm.beta)
library(semTools)

# Load in data 
df <- ## add csv file here

####################################################  
###### Section 1 - Z Score and average variables 
####################################################  
# MASQ
# Calculate Z-scores
Z.MASQ.AA <- scale(df$MASQ.AA)
Z.MASQ.AD <- scale(df$MASQ.AD)
Z.MASQ.Anx <- scale(df$MASQ.Anx)
Z.MASQ.Dep <- scale(df$MASQ.Dep)
# Now average
df$Zd_Anx_combo <- rowMeans(cbind(Z.MASQ.AA, Z.MASQ.Anx))
df$Zd_Dep_combo <- rowMeans(cbind(Z.MASQ.AD, Z.MASQ.Dep))

# eMINI
# Panic disorder combo
Z.panicDis <- scale(df$score6)
Z.agraphobia <- scale(df$score7)
Z.socialPho <- scale(df$score8)
# Now average
df$Zd_panic_disorder_combo <- rowMeans(cbind(Z.panicDis, Z.agraphobia, Z.socialPho))

# Calculate SRP total score
df <- df %>%
  mutate(SRP_new_total = SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2)

# If then using Onyx, will need to save the dataframe here with the  Z scored combined variables from above.
# (Note: depending on format, may also need to rename some variables e.g. STAI.TOT to STAI_TOT)

#########################################################  
###### Section 2 - specify the models (exported from Onyx) 
###### and extract scores for the latent variables
######################################################### 

###### 1) Bifactor Model

# This model specification was automatically generated by Onyx:
bi_model<-"
! regressions 
   p_factor=~p_factor__STAI_TOT*STAI_TOT
   Internalising=~Internalising__STAI_TOT*STAI_TOT
   p_factor=~p_factor__CESD_TOT*CESD_TOT
   Internalising=~Internalising__CESD_TOT*CESD_TOT
   p_factor=~p_factor__AUDIT_TOT*AUDIT_TOT
   Externalising=~Externalising__AUDIT_TOT*AUDIT_TOT
   p_factor=~p_factor__RDU_TOT*RDU_TOT
   Externalising=~Externalising__RDU_TOT*RDU_TOT
   p_factor=~p_factor__Zd_Anx_combo*Zd_Anx_combo
   Internalising=~Internalising__Zd_Anx_combo*Zd_Anx_combo
   p_factor=~p_factor__Zd_Dep_combo*Zd_Dep_combo
   Internalising=~Internalising__Zd_Dep_combo*Zd_Dep_combo
   p_factor=~p_factor__Zd_panic_disorder_combo*Zd_panic_disorder_combo
   Internalising=~Internalising__Zd_panic_disorder_combo*Zd_panic_disorder_combo
   p_factor=~p_factor__score19*score19
   p_factor=~p_factor__score9*score9
   p_factor=~p_factor__score5*score5
   Externalising=~Externalising__score19*score19
   p_factor=~p_factor__score22*score22
! residuals, variances and covariances
   p_factor ~~ 1.0*p_factor
   Internalising ~~ 1.0*Internalising
   Externalising ~~ 1.0*Externalising
   STAI_TOT ~~ VAR_STAI_TOT*STAI_TOT
   CESD_TOT ~~ VAR_CESD_TOT*CESD_TOT
   AUDIT_TOT ~~ VAR_AUDIT_TOT*AUDIT_TOT
   RDU_TOT ~~ VAR_RDU_TOT*RDU_TOT
   Zd_Anx_combo ~~ VAR_Zd_Anx_combo*Zd_Anx_combo
   Zd_Dep_combo ~~ VAR_Zd_Dep_combo*Zd_Dep_combo
   Zd_panic_disorder_combo ~~ VAR_Zd_panic_disorder_combo*Zd_panic_disorder_combo
   score19 ~~ VAR_score19*score19
   score9 ~~ VAR_score9*score9
   score5 ~~ VAR_score5*score5
   score22 ~~ VAR_score22*score22
   p_factor ~~ 0.0*Internalising
   p_factor ~~ 0.0*Externalising
   Internalising ~~ 0.0*Externalising
! observed means
   STAI_TOT~1;
   CESD_TOT~1;
   AUDIT_TOT~1;
   RDU_TOT~1;
   Zd_Anx_combo~1;
   Zd_Dep_combo~1;
   Zd_panic_disorder_combo~1;
   score19~1;
   score9~1;
   score5~1;
   score22~1;
";

# Model fit and summary
bi_fit<-lavaan(bi_model, data=df, model.type="sem", fixed.x=FALSE, missing="FIML");
summary(bi_fit, fit.measures=TRUE);
standardizedSolution(bi_fit)
bi_factor_model_loadings <- inspect(bi_fit, what = "std")[["lambda"]]

# Get omega hierarchical for each factor in the model, plus omega total
compRelSEM(bi_fit, return.total=TRUE)

# Get latent variable estimates and append to data
bi_idx <- lavInspect(bi_fit, "case.idx")
bi_fscores <- lavPredict(bi_fit)
## loop over factors
for (fs in colnames(bi_fscores)) {
  df[bi_idx, fs] <- bi_fscores[ , fs]
}

# Rename to clarify they're estimated from the bifactor model
df <- rename(df, p_factor_bi = p_factor, internalising_bi = Internalising, externalising_bi = Externalising)

###### 2) Higher-order Model
# This model specification was automatically generated by Onyx:
hi_model<-"
! regressions 
   Internalising=~Internalising__STAI_TOT*STAI_TOT
   Internalising=~Internalising__CESD_TOT*CESD_TOT
   Externalising=~Externalising__AUDIT_TOT*AUDIT_TOT
   Externalising=~Externalising__RDU_TOT*RDU_TOT
   Internalising=~Internalising__Zd_Anx_combo*Zd_Anx_combo
   Internalising=~Internalising__Zd_Dep_combo*Zd_Dep_combo
   Internalising=~Internalising__Zd_panic_disorder_combo*Zd_panic_disorder_combo
   Externalising=~Externalising__score19*score19
   p_factor=~p_factor__score9*score9
   p_factor=~p_factor__score5*score5
   p_factor=~p_factor__score22*score22
   p_factor=~p_factor__Internalising*Internalising
   p_factor=~p_factor__Externalising*Externalising
! residuals, variances and covariances
   p_factor ~~ 1.0*p_factor
   Internalising ~~ 1.0*Internalising
   Externalising ~~ 1.0*Externalising
   STAI_TOT ~~ VAR_STAI_TOT*STAI_TOT
   CESD_TOT ~~ VAR_CESD_TOT*CESD_TOT
   AUDIT_TOT ~~ VAR_AUDIT_TOT*AUDIT_TOT
   RDU_TOT ~~ VAR_RDU_TOT*RDU_TOT
   Zd_Anx_combo ~~ VAR_Zd_Anx_combo*Zd_Anx_combo
   Zd_Dep_combo ~~ VAR_Zd_Dep_combo*Zd_Dep_combo
   Zd_panic_disorder_combo ~~ VAR_Zd_panic_disorder_combo*Zd_panic_disorder_combo
   score19 ~~ VAR_score19*score19
   score9 ~~ VAR_score9*score9
   score5 ~~ VAR_score5*score5
   score22 ~~ VAR_score22*score22
   Internalising ~~ 0.0*Externalising
! observed means
   STAI_TOT~1;
   CESD_TOT~1;
   AUDIT_TOT~1;
   RDU_TOT~1;
   Zd_Anx_combo~1;
   Zd_Dep_combo~1;
   Zd_panic_disorder_combo~1;
   score19~1;
   score9~1;
   score5~1;
   score22~1;
";
# Model fit and summary
hi_fit<-lavaan(hi_model, data=df, model.type="sem", fixed.x=FALSE, missing="FIML");
summary(hi_fit, fit.measures=TRUE);
standardizedSolution(hi_fit)
hi_factor_model_loadings <- inspect(hi_fit, what = "std")[["lambda"]]

# Get omega hierarchical for each factor in the model, plus omega total
compRelSEM(hi_fit, higher="p_factor", return.total=TRUE)

# Get latent variable estimates and append to data 
# (used for sensitivity analyses in section 6)
hi_idx <- lavInspect(hi_fit, "case.idx")
hi_fscores <- lavPredict(hi_fit)
## loop over factors
for (fs in colnames(hi_fscores)) {
  df[hi_idx, fs] <- hi_fscores[ , fs]
}
head(df)

# Rename to clarify they're estimated from the hierarchical model
df <- rename(df, p_factor_hi = p_factor, internalising_hi = Internalising, externalising_hi = Externalising)

####################################################  
###### Section 3 - REGRESSION MODELS
###### and assess residuals 
####################################################  

###### 1) BIFACTOR MODEL

# Run linear regressions predicting int/ext/p from SRP facets and covariates (sex, SES)
# P Factor
lm_p = lm(p_factor_bi ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_p)
lm.beta(lm_p)
plot(lm_p$residuals, pch = 16, col = "red") 
hist(lm_p$residuals) 
qqnorm(lm_p$residuals)
qqline(lm_p$residuals)
summary(lm_p$residuals)
plot(cooks.distance(lm_p), pch = 16, col = "blue") 
cooksd <- cooks.distance(lm_p, sort=TRUE)
vif(lm_p) 

# Externalising
lm_ext = lm(externalising_bi ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_ext)
lm.beta(lm_ext)
plot(lm_ext$residuals, pch = 16, col = "red")
hist(lm_ext$residuals)
qqnorm(lm_ext$residuals)
qqline(lm_ext$residuals)
summary(lm_ext$residuals)
shapiro.test(lm_ext$residuals)
plot(cooks.distance(lm_ext), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd <- cooks.distance(lm_ext, sort=TRUE)
vif(lm_ext) 

# Internalising
lm_int = lm(internalising_bi ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_int)
tab_model(lm_int)
lm.beta(lm_int)
plot(lm_int$residuals, pch = 16, col = "red")
hist(lm_int$residuals)
summary(lm_int$residuals)
qqnorm(lm_int$residuals)
qqline(lm_int$residuals)
shapiro.test(lm_int$residuals)
plot(cooks.distance(lm_int), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd <- cooks.distance(lm_int, sort=TRUE)
vif(lm_int) 

## Because the residuals are not normally distributed, log-transform the outcome/response variable (p, int, ext)

df$p_factor_bi_log <- log(2+df$p_factor_bi)
hist(df$p_factor_bi_log)
summary(df$p_factor_bi_log)

df$externalising_bi_log <- log(2+df$externalising_bi)
hist(df$externalising_bi_log)
summary(df$externalising_bi_log)

df$internalising_bi_log <- log(2+df$internalising_bi)
hist(df$internalising_bi_log)
summary(df$internalising_bi_log)

## Now run the regression models again (and assess residuals)

## Run regressions with log transformed outcome variables
# P Factor
lm_p = lm(p_factor_bi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_p)
lm.beta(lm_p)
plot(lm_p$residuals, pch = 16, col = "red") 
hist(lm_p$residuals) 
qqnorm(lm_p$residuals)
qqline(lm_p$residuals)
summary(lm_p$residuals)
plot(cooks.distance(lm_p), pch = 16, col = "blue") 
cooksd <- cooks.distance(lm_p, sort=TRUE)
vif(lm_p) 

# Externalising
lm_ext = lm(externalising_bi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_ext)
lm.beta(lm_ext)
plot(lm_ext$residuals, pch = 16, col = "red")
hist(lm_ext$residuals)
qqnorm(lm_ext$residuals)
qqline(lm_ext$residuals)
summary(lm_ext$residuals)
plot(cooks.distance(lm_ext), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd <- cooks.distance(lm_ext, sort=TRUE)
vif(lm_ext) 

# Internalising
lm_int = lm(internalising_bi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_int)
tab_model(lm_int)
lm.beta(lm_int)
plot(lm_int$residuals, pch = 16, col = "red")
hist(lm_int$residuals)
summary(lm_int$residuals)
qqnorm(lm_int$residuals)
qqline(lm_int$residuals)
plot(cooks.distance(lm_int), pch = 16, col = "blue") #Plot the Cooks Distances.
summary(cooks.distance(lm_int))
cooksd <- cooks.distance(lm_int, sort=TRUE)
vif(lm_int) 

######## 2) Higher-order model
## Run regressions with raw (i.e. non transformed) data

# P Factor
lm_p = lm(p_factor_hi ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_p)
lm.beta(lm_p)
plot(lm_p$residuals, pch = 16, col = "red") 
hist(lm_p$residuals) 
qqnorm(lm_p$residuals)
qqline(lm_p$residuals)
summary(lm_p$residuals)
plot(cooks.distance(lm_p), pch = 16, col = "blue") 
cooksd <- cooks.distance(lm_p, sort=TRUE)
vif(lm_p) 

# Externalising
lm_ext = lm(externalising_hi ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_ext)
lm.beta(lm_ext)
plot(lm_ext$residuals, pch = 16, col = "red")
hist(lm_ext$residuals)
qqnorm(lm_ext$residuals)
qqline(lm_ext$residuals)
summary(lm_ext$residuals)
plot(cooks.distance(lm_ext), pch = 16, col = "blue") 
cooksd <- cooks.distance(lm_ext, sort=TRUE)
vif(lm_ext) 

# Internalising
lm_int = lm(internalising_hi ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_int)
tab_model(lm_int)
lm.beta(lm_int)
plot(lm_int$residuals, pch = 16, col = "red")
hist(lm_int$residuals)
summary(lm_int$residuals)
qqnorm(lm_int$residuals)
qqline(lm_int$residuals)
plot(cooks.distance(lm_int), pch = 16, col = "blue") 
cooksd <- cooks.distance(lm_int, sort=TRUE)
vif(lm_int) 

#### Residuals not normally distributed
#### therefore log transform p/int/ext
df$p_factor_hi_log <- log(2+df$p_factor_hi)
hist(df$p_factor_hi_log)
summary(df$p_factor_hi_log)

df$externalising_hi_log <- log(2+df$externalising_hi)
hist(df$externalising_hi_log)
summary(df$externalising_hi_log)

df$internalising_hi_log <- log(2+df$internalising_hi)
hist(df$internalising_hi_log)
summary(df$internalising_hi_log)

## Run regressions with log transformed outcome variables
# P Factor
lm_p = lm(p_factor_hi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_p)
lm.beta(lm_p)
plot(lm_p$residuals, pch = 16, col = "red") 
hist(lm_p$residuals) 
qqnorm(lm_p$residuals)
qqline(lm_p$residuals)
summary(lm_p$residuals)
plot(cooks.distance(lm_p), pch = 16, col = "blue") 
cooksd <- cooks.distance(lm_p, sort=TRUE)
vif(lm_p) 

# Externalising
lm_ext = lm(externalising_hi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_ext)
lm.beta(lm_ext)
plot(lm_ext$residuals, pch = 16, col = "red")
hist(lm_ext$residuals)
qqnorm(lm_ext$residuals)
qqline(lm_ext$residuals)
summary(lm_ext$residuals)
plot(cooks.distance(lm_ext), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd <- cooks.distance(lm_ext, sort=TRUE)
vif(lm_ext) 

# Internalising
lm_int = lm(internalising_hi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_int)
tab_model(lm_int)
lm.beta(lm_int)
plot(lm_int$residuals, pch = 16, col = "red")
hist(lm_int$residuals)
summary(lm_int$residuals)
qqnorm(lm_int$residuals)
qqline(lm_int$residuals)
plot(cooks.distance(lm_int), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd <- cooks.distance(lm_int, sort=TRUE)
vif(lm_int) 


########################################################  
###### Save regression models to tables (to copy into word)
########################################################  

# Final models (log transformed outcome variables)
# bifactor
lm_p_bi = lm(p_factor_bi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
lm_ext_bi = lm(externalising_bi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
lm_int_bi = lm(internalising_bi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)

# Higher-order
lm_p_hi = lm(p_factor_hi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
lm_ext_hi = lm(externalising_hi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
lm_int_hi = lm(internalising_hi_log ~ SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)

# Present estimates from bifactor or higher-order side-by-side
# p
tab_model(lm_p_bi, lm_p_hi, show.stat=TRUE, collapse.ci=TRUE, string.est="Standardised Coefficient (95% CI)", string.stat = "t")
# get F stat from summary (not in tab model)
summary(lm_p_bi)
summary(lm_p_hi)

# int
tab_model(lm_int_bi, lm_int_hi, show.stat=TRUE, collapse.ci=TRUE, string.est="Standardised Coefficient (95% CI)", string.stat = "t")
summary(lm_int_bi)
summary(lm_int_hi)
# ext
tab_model(lm_ext_bi, lm_ext_hi, show.stat=TRUE, collapse.ci=TRUE, string.est="Standardised Coefficient (95% CI)", string.stat = "t")
summary(lm_ext_bi)
summary(lm_ext_hi)

####################################
###### SUPPLEMENTARY ANALYSES ###### 
####################################

# Incorporate the SRP factors (and sex and SES) into the SEM framework
# NB: for bifactor and higher-order models

# This model specification was automatically generated by Onyx
#
bi_SRP_model<-"
! regressions 
   p_factor=~p_factor__score22*score22
   p_factor=~p_factor__score5*score5
   p_factor=~p_factor__score9*score9
   p_factor=~p_factor__score19*score19
   Internalising=~Internalising__Zd_panic_disorder_combo*Zd_panic_disorder_combo
   p_factor=~p_factor__Zd_panic_disorder_combo*Zd_panic_disorder_combo
   Internalising=~Internalising__Zd_Dep_combo*Zd_Dep_combo
   p_factor=~p_factor__Zd_Dep_combo*Zd_Dep_combo
   Internalising=~Internalising__Zd_Anx_combo*Zd_Anx_combo
   p_factor=~p_factor__Zd_Anx_combo*Zd_Anx_combo
   p_factor=~p_factor__RDU_TOT*RDU_TOT
   p_factor=~p_factor__AUDIT_TOT*AUDIT_TOT
   Internalising=~Internalising__CESD_TOT*CESD_TOT
   p_factor=~p_factor__CESD_TOT*CESD_TOT
   Internalising=~Internalising__STAI_TOT*STAI_TOT
   p_factor=~p_factor__STAI_TOT*STAI_TOT
   Externalising=~Externalising__score19*score19
   Externalising=~Externalising__RDU_TOT*RDU_TOT
   Externalising=~Externalising__AUDIT_TOT*AUDIT_TOT
   Externalising=~Externalising__SRP_Ans_2*SRP_Ans_2
   Externalising=~Externalising__SRP_Aff*SRP_Aff
   Externalising=~Externalising__SRP_Int*SRP_Int
   Externalising=~Externalising__SRP_Life*SRP_Life
   Internalising=~Internalising__SRP_Ans_2*SRP_Ans_2
   Internalising=~Internalising__SRP_Aff*SRP_Aff
   Internalising=~Internalising__SRP_Int*SRP_Int
   Internalising=~Internalising__SRP_Life*SRP_Life
   p_factor=~p_factor__SRP_Ans_2*SRP_Ans_2
   p_factor=~p_factor__SRP_Aff*SRP_Aff
   p_factor=~p_factor__SRP_Int*SRP_Int
   p_factor=~p_factor__SRP_Life*SRP_Life
   p_factor=~p_factor__SES_AV*SES_AV
   p_factor=~p_factor__sex*sex
! residuals, variances and covariances
   p_factor ~~ 1.0*p_factor
   Internalising ~~ 1.0*Internalising
   Externalising ~~ 1.0*Externalising
   SRP_Life ~~ VAR_SRP_Life*SRP_Life
   SRP_Int ~~ VAR_SRP_Int*SRP_Int
   SRP_Aff ~~ VAR_SRP_Aff*SRP_Aff
   SRP_Ans_2 ~~ VAR_SRP_Ans_2*SRP_Ans_2
   score22 ~~ VAR_score22*score22
   score5 ~~ VAR_score5*score5
   score9 ~~ VAR_score9*score9
   score19 ~~ VAR_score19*score19
   Zd_panic_disorder_combo ~~ VAR_Zd_panic_disorder_combo*Zd_panic_disorder_combo
   Zd_Dep_combo ~~ VAR_Zd_Dep_combo*Zd_Dep_combo
   Zd_Anx_combo ~~ VAR_Zd_Anx_combo*Zd_Anx_combo
   RDU_TOT ~~ VAR_RDU_TOT*RDU_TOT
   AUDIT_TOT ~~ VAR_AUDIT_TOT*AUDIT_TOT
   CESD_TOT ~~ VAR_CESD_TOT*CESD_TOT
   STAI_TOT ~~ VAR_STAI_TOT*STAI_TOT
   sex ~~ VAR_sex*sex
   SES_AV ~~ VAR_SES_AV*SES_AV
   p_factor ~~ 0.0*Internalising
   p_factor ~~ 0.0*Externalising
   Internalising ~~ 0.0*Externalising
! observed means
   STAI_TOT~1;
   CESD_TOT~1;
   AUDIT_TOT~1;
   RDU_TOT~1;
   Zd_Anx_combo~1;
   Zd_Dep_combo~1;
   Zd_panic_disorder_combo~1;
   score19~1;
   score9~1;
   score5~1;
   score22~1;
   SRP_Ans_2~1;
   SRP_Aff~1;
   SRP_Int~1;
   SRP_Life~1;
   sex~1;
   SES_AV~1;
";

bi_SRP_model_result <-lavaan(bi_SRP_model, data=df, model.type="sem", fixed.x=FALSE, missing="FIML");
summary(bi_SRP_model_result, fit.measures=TRUE);
bi_SRP_model_loadings <- inspect(bi_SRP_model_result, what = "std")[["lambda"]]

# Get omega hierarchical for each factor in the model, plus omega 'total'
compRelSEM(bi_SRP_model_result, return.total=TRUE)

### Higher-order model:
higher_SRP_model<-"
! regressions 
   Internalising=~Internalising__STAI_TOT*STAI_TOT
   Internalising=~Internalising__CESD_TOT*CESD_TOT
   Externalising=~Externalising__AUDIT_TOT*AUDIT_TOT
   Externalising=~Externalising__RDU_TOT*RDU_TOT
   Internalising=~Internalising__Zd_Anx_combo*Zd_Anx_combo
   Internalising=~Internalising__Zd_Dep_combo*Zd_Dep_combo
   Internalising=~Internalising__Zd_panic_disorder_combo*Zd_panic_disorder_combo
   Externalising=~Externalising__score19*score19
   p_factor=~p_factor__score9*score9
   p_factor=~p_factor__score5*score5
   p_factor=~p_factor__score22*score22
   Internalising=~Internalising__SRP_Int*SRP_Int
   Internalising=~Internalising__SRP_Aff*SRP_Aff
   Internalising=~Internalising__SRP_Life*SRP_Life
   Internalising=~Internalising__SRP_Ans_2*SRP_Ans_2
   Externalising=~Externalising__SRP_Int*SRP_Int
   Externalising=~Externalising__SRP_Aff*SRP_Aff
   Externalising=~Externalising__SRP_Life*SRP_Life
   Externalising=~Externalising__SRP_Ans_2*SRP_Ans_2
   p_factor=~p_factor__SRP_Ans_2*SRP_Ans_2
   p_factor=~p_factor__SRP_Life*SRP_Life
   p_factor=~p_factor__SRP_Aff*SRP_Aff
   p_factor=~p_factor__SRP_Int*SRP_Int
   p_factor=~p_factor__SES_AV*SES_AV
   p_factor=~p_factor__sex*sex
   p_factor=~p_factor__Internalising*Internalising
   p_factor=~p_factor__Externalising*Externalising
! residuals, variances and covariances
   p_factor ~~ 1.0*p_factor
   Internalising ~~ 1.0*Internalising
   Externalising ~~ 1.0*Externalising
   STAI_TOT ~~ VAR_STAI_TOT*STAI_TOT
   CESD_TOT ~~ VAR_CESD_TOT*CESD_TOT
   AUDIT_TOT ~~ VAR_AUDIT_TOT*AUDIT_TOT
   RDU_TOT ~~ VAR_RDU_TOT*RDU_TOT
   Zd_Anx_combo ~~ VAR_Zd_Anx_combo*Zd_Anx_combo
   Zd_Dep_combo ~~ VAR_Zd_Dep_combo*Zd_Dep_combo
   Zd_panic_disorder_combo ~~ VAR_Zd_panic_disorder_combo*Zd_panic_disorder_combo
   score19 ~~ VAR_score19*score19
   score9 ~~ VAR_score9*score9
   score5 ~~ VAR_score5*score5
   score22 ~~ VAR_score22*score22
   SRP_Int ~~ VAR_SRP_Int*SRP_Int
   SRP_Aff ~~ VAR_SRP_Aff*SRP_Aff
   SRP_Life ~~ VAR_SRP_Life*SRP_Life
   SRP_Ans_2 ~~ VAR_SRP_Ans_2*SRP_Ans_2
   sex ~~ VAR_sex*sex
   SES_AV ~~ VAR_SES_AV*SES_AV
   Internalising ~~ 0.0*Externalising
! observed means
   STAI_TOT~1;
   CESD_TOT~1;
   AUDIT_TOT~1;
   RDU_TOT~1;
   Zd_Anx_combo~1;
   Zd_Dep_combo~1;
   Zd_panic_disorder_combo~1;
   score19~1;
   score9~1;
   score5~1;
   score22~1;
   SRP_Int~1;
   SRP_Aff~1;
   SRP_Life~1;
   SRP_Ans_2~1;
   sex~1;
   SES_AV~1;
";

higher_order_SRP_model_result <-lavaan(higher_SRP_model, data=df, model.type="sem", fixed.x=FALSE, missing="FIML");
summary(higher_order_SRP_model_result, fit.measures=TRUE);
higher_order_SRP_model_loadings <- inspect(higher_order_SRP_model_result, what = "std")[["lambda"]]

compRelSEM(higher_order_SRP_model_result, higher="p_factor", return.total=TRUE)