## Code for the paper 'Psychopathic traits and their relationship with vulnerability to 
## general psychopathology in a young adult sample’ (Carlisi, Fielder et al., in prep)

# Jennifer Fielder - jennifer.fielder.21@ucl.ac.uk
# May 2023

# Load dependencies
library(lavaan)
library(dplyr)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
library(ggplot2)
library(car)

# Load in data 
df <- ## add csv file here

####################################################  
###### Section 1 - Z Score and average variables 
####################################################  
# MASQ
# Calculate Z-scores
Z.MASQ.AA <- scale(df$MASQ.AA)
Z.MASQ.AD <- scale(df$MASQ.AD)
Z.MASQ.Anx <- scale(df$MASQ.Anx)
Z.MASQ.Dep <- scale(df$MASQ.Dep)
# Now average
df$Zd_Anx_combo <- rowMeans(cbind(Z.MASQ.AA, Z.MASQ.Anx))
df$Zd_Dep_combo <- rowMeans(cbind(Z.MASQ.AD, Z.MASQ.Dep))

# eMINI
# Panic disorder combo
Z.panicDis <- scale(df$score6)
Z.agraphobia <- scale(df$score7)
Z.socialPho <- scale(df$score8)
# Now average
df$Zd_panic_disorder_combo <- rowMeans(cbind(Z.panicDis, Z.agraphobia, Z.socialPho))

# If then using Onyx, will need to save the dataframe here with the  Z scored combined variables from above.
# (Note: depending on format, may also need to rename some variables e.g. STAI.TOT to STAI_TOT)

#########################################################  
###### Section 2 - specify the models (exported from Onyx) 
###### and extract scores for the latent variables
######################################################### 

###### 1) Bifactor Model

# This model specification was automatically generated by Onyx:
bi_model<-"
! regressions 
   p_factor=~p_factor__STAI_TOT*STAI_TOT
   Internalising=~Internalising__STAI_TOT*STAI_TOT
   p_factor=~p_factor__CESD_TOT*CESD_TOT
   Internalising=~Internalising__CESD_TOT*CESD_TOT
   p_factor=~p_factor__AUDIT_TOT*AUDIT_TOT
   Externalising=~Externalising__AUDIT_TOT*AUDIT_TOT
   p_factor=~p_factor__RDU_TOT*RDU_TOT
   Externalising=~Externalising__RDU_TOT*RDU_TOT
   p_factor=~p_factor__Zd_Anx_combo*Zd_Anx_combo
   Internalising=~Internalising__Zd_Anx_combo*Zd_Anx_combo
   p_factor=~p_factor__Zd_Dep_combo*Zd_Dep_combo
   Internalising=~Internalising__Zd_Dep_combo*Zd_Dep_combo
   p_factor=~p_factor__Zd_panic_disorder_combo*Zd_panic_disorder_combo
   Internalising=~Internalising__Zd_panic_disorder_combo*Zd_panic_disorder_combo
   p_factor=~p_factor__score19*score19
   p_factor=~p_factor__score9*score9
   p_factor=~p_factor__score5*score5
   Externalising=~Externalising__score19*score19
   p_factor=~p_factor__score22*score22
! residuals, variances and covariances
   p_factor ~~ 1.0*p_factor
   Internalising ~~ 1.0*Internalising
   Externalising ~~ 1.0*Externalising
   Internalising ~~ COV_Internalising_Externalising*Externalising
   STAI_TOT ~~ VAR_STAI_TOT*STAI_TOT
   CESD_TOT ~~ VAR_CESD_TOT*CESD_TOT
   AUDIT_TOT ~~ VAR_AUDIT_TOT*AUDIT_TOT
   RDU_TOT ~~ VAR_RDU_TOT*RDU_TOT
   Zd_Anx_combo ~~ VAR_Zd_Anx_combo*Zd_Anx_combo
   Zd_Dep_combo ~~ VAR_Zd_Dep_combo*Zd_Dep_combo
   Zd_panic_disorder_combo ~~ VAR_Zd_panic_disorder_combo*Zd_panic_disorder_combo
   score19 ~~ VAR_score19*score19
   score9 ~~ VAR_score9*score9
   score5 ~~ VAR_score5*score5
   score22 ~~ VAR_score22*score22
   p_factor ~~ 0.0*Internalising
   p_factor ~~ 0.0*Externalising
! observed means
   STAI_TOT~1;
   CESD_TOT~1;
   AUDIT_TOT~1;
   RDU_TOT~1;
   Zd_Anx_combo~1;
   Zd_Dep_combo~1;
   Zd_panic_disorder_combo~1;
   score19~1;
   score9~1;
   score5~1;
   score22~1;
";

# Model fit and summary
bi_fit<-lavaan(bi_model, data=df, model.type="sem", fixed.x=FALSE, missing="FIML");
summary(bi_fit, fit.measures=TRUE);
standardizedSolution(bi_fit)

# Get latent variable estimates and append to data
bi_idx <- lavInspect(bi_fit, "case.idx")
bi_fscores <- lavPredict(bi_fit)
## loop over factors
for (fs in colnames(bi_fscores)) {
  df[bi_idx, fs] <- bi_fscores[ , fs]
}

# Rename to clarify they're estimated from the bifactor model
df <- rename(df, p_factor_bi = p_factor, internalising_bi = Internalising, externalising_bi = Externalising)

###### 2) Hierarchical Model
# This model specification was automatically generated by Onyx:
hierarchical_model<-"
! regressions 
   Internalising=~Internalising__STAI_TOT*STAI_TOT
   Internalising=~Internalising__CESD_TOT*CESD_TOT
   Externalising=~Externalising__AUDIT_TOT*AUDIT_TOT
   Externalising=~Externalising__RDU_TOT*RDU_TOT
   Internalising=~Internalising__Zd_Anx_combo*Zd_Anx_combo
   Internalising=~Internalising__Zd_Dep_combo*Zd_Dep_combo
   Internalising=~Internalising__Zd_panic_disorder_combo*Zd_panic_disorder_combo
   Externalising=~Externalising__score19*score19
   p_factor=~p_factor__score9*score9
   p_factor=~p_factor__score5*score5
   p_factor=~p_factor__score22*score22
   p_factor=~p_factor__Internalising*Internalising
   p_factor=~p_factor__Externalising*Externalising
! residuals, variances and covariances
   p_factor ~~ 1.0*p_factor
   Internalising ~~ 1.0*Internalising
   Externalising ~~ 1.0*Externalising
   STAI_TOT ~~ VAR_STAI_TOT*STAI_TOT
   CESD_TOT ~~ VAR_CESD_TOT*CESD_TOT
   AUDIT_TOT ~~ VAR_AUDIT_TOT*AUDIT_TOT
   RDU_TOT ~~ VAR_RDU_TOT*RDU_TOT
   Zd_Anx_combo ~~ VAR_Zd_Anx_combo*Zd_Anx_combo
   Zd_Dep_combo ~~ VAR_Zd_Dep_combo*Zd_Dep_combo
   Zd_panic_disorder_combo ~~ VAR_Zd_panic_disorder_combo*Zd_panic_disorder_combo
   score19 ~~ VAR_score19*score19
   score9 ~~ VAR_score9*score9
   score5 ~~ VAR_score5*score5
   score22 ~~ VAR_score22*score22
   Internalising ~~ COV_Internalising_Externalising*Externalising
! observed means
   STAI_TOT~1;
   CESD_TOT~1;
   AUDIT_TOT~1;
   RDU_TOT~1;
   Zd_Anx_combo~1;
   Zd_Dep_combo~1;
   Zd_panic_disorder_combo~1;
   score19~1;
   score9~1;
   score5~1;
   score22~1;
";
# Model fit and summary
hi_fit<-lavaan(hierarchical_model, data=df, model.type="sem", fixed.x=FALSE, missing="FIML");
summary(hi_fit, fit.measures=TRUE);
standardizedSolution(hi_fit)

# Get latent variable estimates and append to data 
# (used for sensitivity analyses in section 6)
hi_idx <- lavInspect(hi_fit, "case.idx")
hi_fscores <- lavPredict(hi_fit)
## loop over factors
for (fs in colnames(hi_fscores)) {
  df[hi_idx, fs] <- hi_fscores[ , fs]
}
head(df)

# Rename to clarify they're estimated from the hierarchical model
df <- rename(df, p_factor_hi = p_factor, internalising_hi = Internalising, externalising_hi = Externalising)

####################################################  
###### Section 3 - Log transform skewed variables 
###### Just with bifactor model estimates
####################################################  

# Look at summary statistics & histograms of the raw values
summary(df$p_factor_bi)
summary(df$internalising_bi)
summary(df$externalising_bi)

hist(df$p_factor_bi)
hist(df$internalising_bi)
hist(df$externalising_bi)

# Log transforms on p/ext/int - include a constant of 2 (to ensure they're positive values)
df$p_factor_bi_log <- log(2+df$p_factor_bi)
hist(df$p_factor_bi_log)
summary(df$p_factor_bi_log)

df$externalising_bi_log <- log(2+df$externalising_bi)
hist(df$externalising_bi_log)
summary(df$externalising_bi_log)

df$internalising_bi_log <- log(2+df$internalising_bi)
hist(df$internalising_bi_log)
summary(df$internalising_bi_log)

## And for the SRP values
summary(df$SRP_Int)
summary(df$SRP_Aff)
summary(df$SRP_Life)
summary(df$SRP_Ans_2)

hist(df$SRP_Int)
hist(df$SRP_Aff)
hist(df$SRP_Life)
hist(df$SRP_Ans_2)

df$SRP_Int_log = log(df$SRP_Int)
hist(df$SRP_Int_log)

df$SRP_Aff_log = log(df$SRP_Aff)
hist(df$SRP_Aff_log)

df$SRP_Life_log = log(df$SRP_Life)
hist(df$SRP_Life_log)

df$SRP_Ans_2_log = log(df$SRP_Ans_2)
hist(df$SRP_Ans_2_log)

summary(df$SRP_Int_log)
summary(df$SRP_Aff_log)
summary(df$SRP_Life_log)
summary(df$SRP_Ans_2_log)

# NB: skewness and tables for descriptive statistics were from JASP

###########################################################  
###### Section 4 - Regressions
###### NB: Regression models also run in JASP to be able to
###### copy across the table. Run in R to make plots.
###########################################################  

##### Using log transformed data
# P Factor
lm_log_p = lm(p_factor_bi_log~SRP_Int_log + SRP_Aff_log + SRP_Life_log + SRP_Ans_2_log + SES_AV + sex, data = df)
summary(lm_log_p)
plot(lm_log_p$residuals, pch = 16, col = "red")
plot(cooks.distance(lm_log_p), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd_p <- cooks.distance(lm_log_p, sort=TRUE)
max(cooksd_p)
vif(lm_log_p)

# Externalising
lm_log_ext = lm(externalising_bi_log~SRP_Int_log + SRP_Aff_log + SRP_Life_log + SRP_Ans_2_log + SES_AV + sex, data = df)
summary(lm_log_ext)
plot(lm_log_ext$residuals, pch = 16, col = "red")
plot(cooks.distance(lm_log_ext), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd_ext <- cooks.distance(lm_log_ext, sort=TRUE)
max(cooksd_ext)
vif(lm_log_ext)

# Internalising
lm_log_int = lm(internalising_bi_log~SRP_Int_log + SRP_Aff_log + SRP_Life_log + SRP_Ans_2_log + SES_AV + sex, data = df)
summary(lm_log_int)
plot(lm_log_int$residuals, pch = 16, col = "red")
plot(cooks.distance(lm_log_int), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd_int <- cooks.distance(lm_log_int, sort=TRUE)
max(cooksd_int)
vif(lm_log_int)

##### Raw Data
# P Factor
lm_p = lm(p_factor_bi~SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_p)
plot(lm_p$residuals, pch = 16, col = "red")
plot(cooks.distance(lm_p), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd <- cooks.distance(lm_p, sort=TRUE)
vif(lm_p)

# Externalising
lm_ext = lm(externalising_bi~SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_ext)
plot(lm_ext$residuals, pch = 16, col = "red")
plot(cooks.distance(lm_ext), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd <- cooks.distance(lm_ext, sort=TRUE)
vif(lm_ext)

# Internalising
lm_int = lm(internalising_bi~SRP_Int + SRP_Aff + SRP_Life + SRP_Ans_2 + SES_AV + sex, data = df)
summary(lm_int)
plot(lm_int$residuals, pch = 16, col = "red")
plot(cooks.distance(lm_int), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd <- cooks.distance(lm_int, sort=TRUE)
vif(lm_int)

####################################################  
###### Section 5 - Plots
####################################################  
# Plots of predicted values
plot_model(lm_log_p, type="pred", terms="SRP_Life_log")+
  labs(x="SRP Lifestyle (log transformed)", y="p factor (log transformed)", title="Predicted values of p factor scores")+
  theme_classic()

plot_model(lm_log_ext, type="pred", terms="SRP_Life_log")+
  labs(x="SRP Lifestyle (log transformed)", y="Externalising (log transformed)", title="Predicted values of externalising")+
  theme_classic()

plot_model(lm_log_int, type="pred", terms="SRP_Aff_log")+
  labs(x="SRP Affective (log transformed)", y="Internalising (log transformed)", title="Predicted values of internalising")+
  theme_classic()

plot_model(lm_log_int, type="pred", terms="SRP_Int_log")+
  labs(x="SRP Interpersonal (log transformed)", y="Internalising (log transformed)", title="Predicted values of internalising")+
  theme_classic()

##################################################################  
###### Section 6 - Sensitivity Analyses
###### (Same analyses as sections as 3 and 4 but for scores derived 
###### from the hierarchical model)
##################################################################  
summary(df$p_factor_hi)
summary(df$internalising_hi)
summary(df$externalising_hi)

df$p_factor_hi_log <- log(2+df$p_factor_hi)
df$externalising_hi_log <- log(2+df$externalising_hi)
df$internalising_hi_log <- log(2+df$internalising_hi)

# P Factor
lm_log_p_hi = lm(p_factor_hi_log~SRP_Int_log + SRP_Aff_log + SRP_Life_log + SRP_Ans_2_log + SES_AV + sex, data = df)
summary(lm_log_p_hi)
plot(lm_log_p_hi$residuals, pch = 16, col = "red")
plot(cooks.distance(lm_log_p_hi), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd_p_hi <- cooks.distance(lm_log_p_hi, sort=TRUE)
max(cooksd_p_hi)
vif(lm_log_p_hi)

# Externalising
lm_log_ext_hi = lm(externalising_hi_log~SRP_Int_log + SRP_Aff_log + SRP_Life_log + SRP_Ans_2_log + SES_AV + sex, data = df)
summary(lm_log_ext_hi)
plot(lm_log_ext_hi$residuals, pch = 16, col = "red")
plot(cooks.distance(lm_log_ext_hi), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd_ext_hi <- cooks.distance(lm_log_ext_hi, sort=TRUE)
max(cooksd_ext_hi)
vif(lm_log_ext_hi)

# Internalising
lm_log_int_hi = lm(internalising_hi_log~SRP_Int_log + SRP_Aff_log + SRP_Life_log + SRP_Ans_2_log + SES_AV + sex, data = df)
summary(lm_log_int_hi)
plot(lm_log_int_hi$residuals, pch = 16, col = "red")
plot(cooks.distance(lm_log_int_hi), pch = 16, col = "blue") #Plot the Cooks Distances.
cooksd_int_hi <- cooks.distance(lm_log_int_hi, sort=TRUE)
max(cooksd_int_hi)
vif(lm_log_int_hi)
